# Generated by Django 5.2.8 on 2025-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('review', 'review'), ('done', 'done')], default='to_do', max_length=11)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=6)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
