# Generated by Django 5.2.8 on 2025-11-14 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_alter_ticket_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(related_name='assignee_of_task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
